CREATE TABLE "students"(
    "id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "student_link" VARCHAR(500),
    "enrolment_status" VARCHAR(255) NOT NULL,
    "year" BIGINT NOT NULL,
    "account_name" VARCHAR(255) NOT NULL,
    "account_link" VARCHAR(500),
    "attendance_count" BIGINT NOT NULL,
    "last_attendance" DATE,
    "last_assessment" DATE,
    "active_lps" BIGINT,
    "skills_assigned" BIGINT,
    "skills_mastered" BIGINT,
    "last_lp_update" DATE,
    "last_pr_sent" DATE,
    "last_progress_check" DATE,
    "delivery" VARCHAR(255),
    "virtual_center" VARCHAR(255),
    "mathnasium_id" BIGINT,
    "total_lp_skills_mastered" BIGINT,
    "total_lp_skills" BIGINT,
    "skills_mastered_percent" DECIMAL(5,2),
    PRIMARY KEY("id")
);